# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddIngredientWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddIngredientWidget(object):
    def setupUi(self, AddIngredientWidget):
        AddIngredientWidget.setObjectName("AddIngredientWidget")
        AddIngredientWidget.resize(433, 88)
        self.horizontalLayout = QtWidgets.QHBoxLayout(AddIngredientWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineIngredientName = QtWidgets.QLineEdit(AddIngredientWidget)
        self.lineIngredientName.setClearButtonEnabled(True)
        self.lineIngredientName.setObjectName("lineIngredientName")
        self.horizontalLayout.addWidget(self.lineIngredientName)
        self.dspnAmount = QtWidgets.QDoubleSpinBox(AddIngredientWidget)
        self.dspnAmount.setSingleStep(0.25)
        self.dspnAmount.setObjectName("dspnAmount")
        self.horizontalLayout.addWidget(self.dspnAmount)
        self.comboUnits = QtWidgets.QComboBox(AddIngredientWidget)
        self.comboUnits.setFrame(True)
        self.comboUnits.setObjectName("comboUnits")
        self.comboUnits.addItem("")
        self.comboUnits.setItemText(0, "")
        self.comboUnits.addItem("")
        self.comboUnits.addItem("")
        self.comboUnits.addItem("")
        self.comboUnits.addItem("")
        self.horizontalLayout.addWidget(self.comboUnits)

        self.retranslateUi(AddIngredientWidget)
        QtCore.QMetaObject.connectSlotsByName(AddIngredientWidget)

    def retranslateUi(self, AddIngredientWidget):
        _translate = QtCore.QCoreApplication.translate
        AddIngredientWidget.setWindowTitle(_translate("AddIngredientWidget", "Form"))
        self.lineIngredientName.setPlaceholderText(_translate("AddIngredientWidget", "add ingredient..."))
        self.comboUnits.setToolTip(_translate("AddIngredientWidget", "Select units"))
        self.comboUnits.setItemText(1, _translate("AddIngredientWidget", "count"))
        self.comboUnits.setItemText(2, _translate("AddIngredientWidget", "cups"))
        self.comboUnits.setItemText(3, _translate("AddIngredientWidget", "tbsp"))
        self.comboUnits.setItemText(4, _translate("AddIngredientWidget", "tsp"))
